### ISSUE TITLE
I can't see japanese description page

### ISSUE THREAD

**Issue by syunsuke** [CheckiO-Missions/checkio-mission-all-the-same#8]
Hi.

I want to report something.

When I click "JP" link in the upper-right of the page, I meet "404 not found".
I wonder if other parsons will meet "not found page" too or only I do??

I can find "translations/jp/info/task_description.html" file exists on the github's repository.
so I don't know Why it happens.

By the way, this issues is my first issues on my life.
And I am studying English now.
So I may be not able to understand difficult discussion, but I will try to contribute.

thank you

**Comment by oduvan** [comment]
should be fixed.

thanks
